BenLangmead/bowtie2

bowtie2

Ran into the following error after attempting to run Bowtie 2.2.3 on FreeBSD 9.2:
```
$ bowtie2
(ERR): Expected bowtie2 to be in same directory with bowtie2-align:
/opt/bowtie/2.2.3/
Exiting now ...
```
On FreeBSD, the Perl <b>$^O</b> variable is 'freebsd', whereas the code assumes that everything that isn't 'linux' or 'darwin' is Windows.
Per http://www.perlmonks.org/?node_id=845088 , <b>$^O</b> is 'MSWin32' on all flavors of Windows; it would be more portable to assume everything that isn't Windows is *nix.

Treat $^O eq 'MSWin32' as Windows, and assume everything else is *nix.

---

aligner_result.cpp

When calculating the coordinates of the dynamic programming cells that an alignment consists of, the current code does not take soft clipping into account. This means that, when the --local and -a flags are set, different portions of a read that align to the same stretch of a reference sequence are considered redundant and only one is reported.
To fix this, this pull request changes the calculation of these coordinates to use absolute positions in a read rather than positions relative to the first aligned base.   
(The use case that revealed this behavior is when reads consist of concatamers, as in http://www.pnas.org/content/110/49/19872.abstract.)

accounts for soft-clipping in DP redundancy checks

---

Makefile
doc/website/rhsidebar.ssi
ds.h
pat.h

fixes #11
- adds standard variables prefix and bindir
- adds the install target that installs the standard executables to
bindir
This allows to install as follows:
```
$ make DESTDIR=/tmp/bowtie install                                                                                                                         
mkdir -p /tmp/bowtie/usr/local/bin
for file in bowtie2-build-s bowtie2-build-l bowtie2-align-s bowtie2-align-l bowtie2-inspect-s bowtie2-inspect-l bowtie2-inspect bowtie2-build bowtie2 ; do \
cp -f $file /tmp/bowtie/usr/local/bin ; \
done
$ tree /tmp/bowtie/
/tmp/bowtie/
└── usr
└── local
└── bin
├── bowtie2
├── bowtie2-align-l
├── bowtie2-align-s
├── bowtie2-build
├── bowtie2-build-l
├── bowtie2-build-s
├── bowtie2-inspect
├── bowtie2-inspect-l
└── bowtie2-inspect-s
3 …
```

make install target

---

processor_support.h

The intel compiler fails with this error:
`error: argument of type "void *" is incompatible with parameter of type "int *"`

Fix __cpuid() argument type

---

Makefile

Static linking is not enabled on Windows because of a missing 'override' directive.

Enable static linking on Windows

---

bt2_build.cpp

With --quiet, bowtie2-build still prints message, added verbose flag.

Added verbose flag to "Building X index"

---

bt2_search.cpp

I had some trouble trying to do this sort of thing:
```
bowtie2 --interleaved -x /path/to/bowtie2_index/hg19 <all kind of stuff here -12, -1, -U ...> r1_r2_interleaved.fastq
```
but this works:
```
bowtie2 -x /path/to/bowtie2_index/hg19 --interleaved r1_r2_interleaved.fastq
```
This doc change describes what worked for me.
I did not test tab5/6 files, but they may have the same usage

Clarifies documentation of how to use --interleaved

---

outq.h

I saw segfaults when running with `--reorder` and `-p` greater than 1.  This is a fix.

fix segfault with --reorder

---

bt2_io.cpp

Verify if input files aren't too short (corrupted). If so, stop the reading routing and throw an error.
Fixes #209

Verify if files aren't too short #209

---

.gitmodules
.travis.yml
Dockerfile-aarch64
Makefile
aligner_sw.h
sse_util.h

Hello @BenLangmead . This PR is to support `bowtie2` to _aarch64_ (ARM 64-bit) environment.
Here is the passed Travis CI.
https://travis-ci.org/BenLangmead/bowtie2/builds/497898138
I am building some bio tools on the ARM environment.
I referred ARM development team's wiki document [1].
The way to run on different architecture has been used for `nanopolish` [2] and PostgreSQL binding [3]. (I contributed).
I also would like to inform you that Red Hat Enterprise Linux 8 started to support ARM 64-bit.
So, it might be a good timing for `bowtie2` to provide the aarch64.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html-single/8.0_beta_release_notes/index#architectures
> The 64-bit ARM architecture
This also helps people to create `bowtie2` aarch64 deb package in …

Support aarch64 (ARM 64-bit)

---

bowtie2

Hello Ben,
We're observing bowtie zombies once in a while, and it seems that happens when bowtie-align fails in such a way that it doesn't try to open files passed in -1 and/or -2 parameters . Then, the feeder sub-processes hang forever in open(fifo) states.
To reproduce, replace $cmd to something else, f.ex. '/bin/false', before it gets executed.
The patch here kills the processes explicitly, and it seems to work fine.
Hope that makes sense,
Dmitry

don't create zombies under race condition

---

Makefile

* use NEWS file time instead of current time
* allow to override hostname via $HOSTNAME
See https://reproducible-builds.org/ for why this is good.
This date call works with GNU date and BSD date.
The alternative to this patch would be to drop both completely.
This PR was done while working on reproducible builds for openSUSE.

Allow for reproducible builds

---

doc/website/rhsidebar.ssi

* Adds links for major-allele human refs
* Removes outdated message about `unzip` and large files
* Removes partial-zip file links.  They're still on the FTP site but I doubt they're needed any more.

Restructure index sidebar and add major-allele indexes

---

blockwise_sa.h

This header file is used in a lot of _.cpp_ files so this warning appears numerous times during a build:
```
./blockwise_sa.h:222:3: warning: field '_done' will be initialized after field 'thread_group_started' [-Wreorder]
_done(NULL)
^
```
Prevented by writing the initialisations in the right order, which also improves the formatting of the code as it no longer needs to fiddle the comma.

Avoid repeated warning from header file

---

Makefile

This PR is to build with the given `CXXFLAGS`.
Current `Makefile` ignore the given `CXXFLAGS` for only non-x86-64 architectures.
I am building with the following `CXXFLAGS`.
```
$ CXXFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection" make
```

Fix to build with the given CXXFLAGS.

---

bt2_dp.cpp
bt2_search.cpp
pat.h

This should fix #311.
`qUpto` was defined as `uint32_t` with a default max number of queries set at `0xffffffff`. When provided with an input file with >= 2^32 queries, the reads at and beyond 2^32 were silently discarded. This patch modifies the type to `uint64_t` and updates the default maximum to `0xffffffffffffffff`. 
The former default was added approximately 10 years ago, which made sense with the generation of sequencing instruments at the time. However, this default presents an issue for Illumina NovaSeq platforms, as they can produce [billions](https://www.illumina.com/systems/sequencing-platforms/novaseq/specifications.html) of sequencing reads per lane. At the moment, users must partition input query files into multiple sets to work around this. However, the current behavior is …

BUG: qupto overflows when there are >= 2**32 query sequences

---

bowtie2

Zstandard is a [relatively] new compression by Yann Collet (Facebook). It combines speed of decompression (like LZ4) with higher compression than GZIP. Very appropriate for long term storage of sequencing data and get quick access to it at the same time. This patch doesn't disrupt any previous functionality.
I rebased it (from a previous patch) to recent Bowtie2 wrapper code. Please merge it.

Adds Zstandard compression input/output

---

CMakeLists.txt

Two typos prevented the option from actually working.

Fix BOWTIE_SHARED_MEM CMake option.

---

aligner_seed.cpp
aligner_seed.h
bt2_idx.h

Profiling shows that we spend a lot of time waiting on access to content of side().
Since access is not sequential, the CPU needs hints ASAP on which cache line will be hit next.
Adding explicit prefetch commands achieves that goal.

Add prefetch commands to speedup countUpToEx

---

Makefile
aligner_cache.h
aligner_seed.cpp
aligner_seed.h
bt2_idx.h

SeedAligner::searchSeedBi used to be completely memory bound (indirectly via Ebwt::countUpToEx), due to irregular memory access pattern.
By interleaving many searchSeedBi loops in a single invocation, the prefetch now has enough latency to be effective.
This required a refactoring of the loop in SeedAligner::searchAllSeeds.
A similar change was made in SeedAligner::exactSweep, too.

Improve prefetch effectiveness by refactoring loops in SeedAligner::searchAllSeeds, SeedAligner::searchSeedBi and SeedAligner::exactSweep

---

aligner_swsse_ee_i16.cpp
aligner_swsse_ee_u8.cpp

Minor code optimization of SwAligner::alignNucleotidesEnd2EndSseU8 and SwAligner::alignNucleotidesEnd2EndSseI16.
Explicitly load pvScore and re-arrange load order to better account for SSE latency.
Also avoid using object globals in inner loop.

Minor optimization of SwAligner::alignNucleotidesEnd2EndSse*

---

bt2_search.cpp
pat.h

DIsk IO can be overlapped with compute, avoiding artificial serialization.
Since true async IO does not exist, I add a dedicated thread that reads for the compute threads in parallel with the compute.

Make reading of buffers fully asynchronous

---

MANUAL

A minus sign was missing on the bam switch

Typo in command line section of the MANUAL

---

AUTHORS

which was removed in https://github.com/BenLangmead/bowtie2/commit/acbc571bf7a637692e71c51e6700e02b23db1c4c

remove mention of TinyThread

---

bt2_search.cpp
pat.h

On small thread count, the polling LockedQueue add substantial overhead to bowtie2,
so we revert back to using the lightweight condition_variable based solution there.
See #465 for details. 
We keep the polling, lock-free version for higher thread counts, to avoid excessive contention on the lock.
See #437 for details.

Add back the condition_variable based LockedQueue for low-thread setups
